openapi: 3.0.1
info:
  title: MyTravelPlan API Documentation
  description: This is the API documentation for MyTravelPlan application.
  version: 0.0.1-SNAPSHOT
servers:
- url: https://localhost:8080
tags: []
paths: {}
components:
  schemas: {}
