package travel.mytravelplan;

import lombok.RequiredArgsConstructor;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import travel.mytravelplan.domain.currency.entity.Currency;
import travel.mytravelplan.domain.currency.enums.CurrencyType;
import travel.mytravelplan.domain.currency.repository.CurrencyRepository;

import java.math.BigDecimal;
import java.util.List;

@Profile("local")
@Component
@Order(1)
@RequiredArgsConstructor
public class CurrencyInitializer implements ApplicationRunner {
    private final CurrencyRepository currencyRepository;

    @Transactional
    @Override
    public void run(ApplicationArguments args) throws Exception {
        List<Currency> currencies = List.of(
            Currency.createCurrency(CurrencyType.AED, new BigDecimal("377.3876")),
            Currency.createCurrency(CurrencyType.AFN, new BigDecimal("20.2634")),
            Currency.createCurrency(CurrencyType.ALL, new BigDecimal("16.6372")),
            Currency.createCurrency(CurrencyType.AMD, new BigDecimal("3.6112")),
            Currency.createCurrency(CurrencyType.ANG, new BigDecimal("774.277")),
            Currency.createCurrency(CurrencyType.AOA, new BigDecimal("1.4844")),
            Currency.createCurrency(CurrencyType.ARS, new BigDecimal("1.0671")),
            Currency.createCurrency(CurrencyType.AUD, new BigDecimal("901.2522")),
            Currency.createCurrency(CurrencyType.AWG, new BigDecimal("774.277")),
            Currency.createCurrency(CurrencyType.AZN, new BigDecimal("814.2918")),
            Currency.createCurrency(CurrencyType.BAM, new BigDecimal("827.5798")),
            Currency.createCurrency(CurrencyType.BBD, new BigDecimal("692.9779")),
            Currency.createCurrency(CurrencyType.BDT, new BigDecimal("11.4269")),
            Currency.createCurrency(CurrencyType.BGN, new BigDecimal("827.5556")),
            Currency.createCurrency(CurrencyType.BHD, new BigDecimal("3686.0528")),
            Currency.createCurrency(CurrencyType.BIF, new BigDecimal("0.4615")),
            Currency.createCurrency(CurrencyType.BMD, new BigDecimal("1385.9558")),
            Currency.createCurrency(CurrencyType.BND, new BigDecimal("1080.1604")),
            Currency.createCurrency(CurrencyType.BOB, new BigDecimal("200.6095")),
            Currency.createCurrency(CurrencyType.BRL, new BigDecimal("255.2115")),
            Currency.createCurrency(CurrencyType.BSD, new BigDecimal("1389.6712")),
            Currency.createCurrency(CurrencyType.BTN, new BigDecimal("15.9571")),
            Currency.createCurrency(CurrencyType.BWP, new BigDecimal("100.2060")),
            Currency.createCurrency(CurrencyType.BYN, new BigDecimal("436.0701")),
            Currency.createCurrency(CurrencyType.BZD, new BigDecimal("694.8356")),
            Currency.createCurrency(CurrencyType.CAD, new BigDecimal("1004.9226")),
            Currency.createCurrency(CurrencyType.CDF, new BigDecimal("0.4773")),
            Currency.createCurrency(CurrencyType.CHF, new BigDecimal("1723.9307")),
            Currency.createCurrency(CurrencyType.CLP, new BigDecimal("1.4411")),
            Currency.createCurrency(CurrencyType.CNY, new BigDecimal("193.5845")),
            Currency.createCurrency(CurrencyType.COP, new BigDecimal("0.3458")),
            Currency.createCurrency(CurrencyType.CRC, new BigDecimal("2.7500")),
            Currency.createCurrency(CurrencyType.CUP, new BigDecimal("57.9030")),
            Currency.createCurrency(CurrencyType.CVE, new BigDecimal("14.7024")),
            Currency.createCurrency(CurrencyType.CZK, new BigDecimal("66.3528")),
            Currency.createCurrency(CurrencyType.DJF, new BigDecimal("7.8194")),
            Currency.createCurrency(CurrencyType.DKK, new BigDecimal("217.3426")),
            Currency.createCurrency(CurrencyType.DOP, new BigDecimal("22.4967")),
            Currency.createCurrency(CurrencyType.DZD, new BigDecimal("10.6977")),
            Currency.createCurrency(CurrencyType.EGP, new BigDecimal("28.6916")),
            Currency.createCurrency(CurrencyType.ERN, new BigDecimal("92.6447")),
            Currency.createCurrency(CurrencyType.ETB, new BigDecimal("9.8364")),
            Currency.createCurrency(CurrencyType.EUR, new BigDecimal("1622.1899")),
            Currency.createCurrency(CurrencyType.FJD, new BigDecimal("614.6875")),
            Currency.createCurrency(CurrencyType.FKP, new BigDecimal("1876.6281")),
            Currency.createCurrency(CurrencyType.FOK, new BigDecimal("217.1952")),
            Currency.createCurrency(CurrencyType.GBP, new BigDecimal("1877.8581")),
            Currency.createCurrency(CurrencyType.GEL, new BigDecimal("514.6636")),
            Currency.createCurrency(CurrencyType.GGP, new BigDecimal("1876.6281")),
            Currency.createCurrency(CurrencyType.GHS, new BigDecimal("122.4302")),
            Currency.createCurrency(CurrencyType.GIP, new BigDecimal("1876.6281")),
            Currency.createCurrency(CurrencyType.GMD, new BigDecimal("19.0698")),
            Currency.createCurrency(CurrencyType.GNF, new BigDecimal("0.1598")),
            Currency.createCurrency(CurrencyType.GTQ, new BigDecimal("181.2095")),
            Currency.createCurrency(CurrencyType.GYD, new BigDecimal("6.6364")),
            Currency.createCurrency(CurrencyType.HKD, new BigDecimal("178.2060")),
            Currency.createCurrency(CurrencyType.HNL, new BigDecimal("52.9691")),
            Currency.createCurrency(CurrencyType.HRK, new BigDecimal("215.1645")),
            Currency.createCurrency(CurrencyType.HTG, new BigDecimal("10.6045")),
            Currency.createCurrency(CurrencyType.HUF, new BigDecimal("4.1188")),
            Currency.createCurrency(CurrencyType.IDR, new BigDecimal("0.08547")),
            Currency.createCurrency(CurrencyType.ILS, new BigDecimal("410.1324")),
            Currency.createCurrency(CurrencyType.IMP, new BigDecimal("1876.6281")),
            Currency.createCurrency(CurrencyType.INR, new BigDecimal("15.9646")),
            Currency.createCurrency(CurrencyType.IQD, new BigDecimal("1.0591")),
            Currency.createCurrency(CurrencyType.IRR, new BigDecimal("0.03253")),
            Currency.createCurrency(CurrencyType.ISK, new BigDecimal("11.3163")),
            Currency.createCurrency(CurrencyType.JEP, new BigDecimal("1876.6281")),
            Currency.createCurrency(CurrencyType.JMD, new BigDecimal("8.6760")),
            Currency.createCurrency(CurrencyType.JOD, new BigDecimal("1960.0441")),
            Currency.createCurrency(CurrencyType.JPY, new BigDecimal("9.4121")),
            Currency.createCurrency(CurrencyType.KES, new BigDecimal("10.7514")),
            Currency.createCurrency(CurrencyType.KGS, new BigDecimal("15.9106")),
            Currency.createCurrency(CurrencyType.KHR, new BigDecimal("0.3455")),
            Currency.createCurrency(CurrencyType.KMF, new BigDecimal("3.2953")),
            Currency.createCurrency(CurrencyType.KRW, new BigDecimal("1.0")),
            Currency.createCurrency(CurrencyType.KWD, new BigDecimal("4554.9227")),
            Currency.createCurrency(CurrencyType.KYD, new BigDecimal("1667.6062")),
            Currency.createCurrency(CurrencyType.KZT, new BigDecimal("2.5857")),
            Currency.createCurrency(CurrencyType.LAK, new BigDecimal("0.06394")),
            Currency.createCurrency(CurrencyType.LBP, new BigDecimal("0.01553")),
            Currency.createCurrency(CurrencyType.LKR, new BigDecimal("4.6229")),
            Currency.createCurrency(CurrencyType.LRD, new BigDecimal("6.9260")),
            Currency.createCurrency(CurrencyType.LSL, new BigDecimal("78.7980")),
            Currency.createCurrency(CurrencyType.LYD, new BigDecimal("256.4500")),
            Currency.createCurrency(CurrencyType.MAD, new BigDecimal("154.0895")),
            Currency.createCurrency(CurrencyType.MDL, new BigDecimal("83.3745")),
            Currency.createCurrency(CurrencyType.MGA, new BigDecimal("0.3136")),
            Currency.createCurrency(CurrencyType.MKD, new BigDecimal("26.3711")),
            Currency.createCurrency(CurrencyType.MMK, new BigDecimal("0.6607")),
            Currency.createCurrency(CurrencyType.MNT, new BigDecimal("0.3894")),
            Currency.createCurrency(CurrencyType.MOP, new BigDecimal("172.9725")),
            Currency.createCurrency(CurrencyType.MRU, new BigDecimal("34.6818")),
            Currency.createCurrency(CurrencyType.MUR, new BigDecimal("30.1824")),
            Currency.createCurrency(CurrencyType.MVR, new BigDecimal("89.8946")),
            Currency.createCurrency(CurrencyType.MWK, new BigDecimal("0.7966")),
            Currency.createCurrency(CurrencyType.MXN, new BigDecimal("73.9461")),
            Currency.createCurrency(CurrencyType.MYR, new BigDecimal("328.7942")),
            Currency.createCurrency(CurrencyType.MZN, new BigDecimal("21.7401")),
            Currency.createCurrency(CurrencyType.NAD, new BigDecimal("78.7980")),
            Currency.createCurrency(CurrencyType.NGN, new BigDecimal("0.9056")),
            Currency.createCurrency(CurrencyType.NIO, new BigDecimal("37.7598")),
            Currency.createCurrency(CurrencyType.NOK, new BigDecimal("135.8412")),
            Currency.createCurrency(CurrencyType.NPR, new BigDecimal("9.9732")),
            Currency.createCurrency(CurrencyType.NZD, new BigDecimal("821.2517")),
            Currency.createCurrency(CurrencyType.OMR, new BigDecimal("3614.2577")),
            Currency.createCurrency(CurrencyType.PAB, new BigDecimal("389.6712")),
            Currency.createCurrency(CurrencyType.PEN, new BigDecimal("393.7871")),
            Currency.createCurrency(CurrencyType.PGK, new BigDecimal("331.3277")),
            Currency.createCurrency(CurrencyType.PHP, new BigDecimal("24.2942")),
            Currency.createCurrency(CurrencyType.PKR, new BigDecimal("4.9082")),
            Currency.createCurrency(CurrencyType.PLN, new BigDecimal("382.2446")),
            Currency.createCurrency(CurrencyType.PYG, new BigDecimal("0.1882")),
            Currency.createCurrency(CurrencyType.QAR, new BigDecimal("381.7778")),
            Currency.createCurrency(CurrencyType.RON, new BigDecimal("320.8278")),
            Currency.createCurrency(CurrencyType.RSD, new BigDecimal("13.8424")),
            Currency.createCurrency(CurrencyType.RUB, new BigDecimal("17.2683")),
            Currency.createCurrency(CurrencyType.RWF, new BigDecimal("0.9568")),
            Currency.createCurrency(CurrencyType.SAR, new BigDecimal("370.5790")),
            Currency.createCurrency(CurrencyType.SBD, new BigDecimal("165.2314")),
            Currency.createCurrency(CurrencyType.SCR, new BigDecimal("94.0653")),
            Currency.createCurrency(CurrencyType.SDG, new BigDecimal("3.1045")),
            Currency.createCurrency(CurrencyType.SEK, new BigDecimal("145.2165")),
            Currency.createCurrency(CurrencyType.SGD, new BigDecimal("1082.9369")),
            Currency.createCurrency(CurrencyType.SHP, new BigDecimal("1876.6281")),
            Currency.createCurrency(CurrencyType.SLE, new BigDecimal("59.8421")),
            Currency.createCurrency(CurrencyType.SLL, new BigDecimal("0.05981")),
            Currency.createCurrency(CurrencyType.SOS, new BigDecimal("2.4273")),
            Currency.createCurrency(CurrencyType.SRD, new BigDecimal("36.7682")),
            Currency.createCurrency(CurrencyType.SSP, new BigDecimal("0.2947")),
            Currency.createCurrency(CurrencyType.STN, new BigDecimal("66.1697")),
            Currency.createCurrency(CurrencyType.SYP, new BigDecimal("0.1076")),
            Currency.createCurrency(CurrencyType.SZL, new BigDecimal("78.7980")),
            Currency.createCurrency(CurrencyType.THB, new BigDecimal("42.7175")),
            Currency.createCurrency(CurrencyType.TJS, new BigDecimal("148.3499")),
            Currency.createCurrency(CurrencyType.TMT, new BigDecimal("396.8954")),
            Currency.createCurrency(CurrencyType.TND, new BigDecimal("482.5647")),
            Currency.createCurrency(CurrencyType.TOP, new BigDecimal("576.8056")),
            Currency.createCurrency(CurrencyType.TRY, new BigDecimal("33.9737")),
            Currency.createCurrency(CurrencyType.TTD, new BigDecimal("205.0000")),
            Currency.createCurrency(CurrencyType.TWD, new BigDecimal("46.2100")),
            Currency.createCurrency(CurrencyType.TZS, new BigDecimal("0.5388")),
            Currency.createCurrency(CurrencyType.UAH, new BigDecimal("33.6014")),
            Currency.createCurrency(CurrencyType.UGX, new BigDecimal("1.0")),
            Currency.createCurrency(CurrencyType.USD, new BigDecimal("1386.6044")),
            Currency.createCurrency(CurrencyType.UYU, new BigDecimal("34.6713")),
            Currency.createCurrency(CurrencyType.UZS, new BigDecimal("0.1102")),
            Currency.createCurrency(CurrencyType.VES, new BigDecimal("10.0659")),
            Currency.createCurrency(CurrencyType.VND, new BigDecimal("0.05318")),
            Currency.createCurrency(CurrencyType.VUV, new BigDecimal("11.6347")),
            Currency.createCurrency(CurrencyType.WST, new BigDecimal("516.8037")),
            Currency.createCurrency(CurrencyType.XAF, new BigDecimal("2.4714")),
            Currency.createCurrency(CurrencyType.XCD, new BigDecimal("514.6931")),
            Currency.createCurrency(CurrencyType.XDR, new BigDecimal("1902.6014")),
            Currency.createCurrency(CurrencyType.XOF, new BigDecimal("2.4714")),
            Currency.createCurrency(CurrencyType.XPF, new BigDecimal("13.5853")),
            Currency.createCurrency(CurrencyType.YER, new BigDecimal("5.7819")),
            Currency.createCurrency(CurrencyType.ZAR, new BigDecimal("78.7785")),
            Currency.createCurrency(CurrencyType.ZMW, new BigDecimal("59.6232")),
            Currency.createCurrency(CurrencyType.ZWL, new BigDecimal("51.9176"))
        );

        currencyRepository.saveAll(currencies);
    }
}
